export default async () => ({
  code: 200,
  data: [
    { ko: '관광명소', en: 'Attractions', categoryGroupCode: 'AT4' },
    { ko: '문화시설', en: 'Cultural Facilities', categoryGroupCode: 'CT1' },
    { ko: '대형마트', en: 'Market', categoryGroupCode: 'MT1' },
    { ko: '편의점', en: 'Convenience Store', categoryGroupCode: 'CS2' },
    { ko: '어린이집, 유치원', en: 'Kindergarden', categoryGroupCode: 'PS3' },
    { ko: '학교', en: 'School', categoryGroupCode: 'SC4' },
    { ko: '학원', en: 'Arcademy', categoryGroupCode: 'AC5' },
    { ko: '주차장', en: 'Parking lot', categoryGroupCode: 'PK6' },
    { ko: '주유소, 충전소', en: 'Gas station', categoryGroupCode: 'OL7' },
    { ko: '지하철역', en: 'Subway', categoryGroupCode: 'SW8' },
    { ko: '은행', en: 'Bank', categoryGroupCode: 'BK9' },
    { ko: '중개업소', en: 'Brokerage', categoryGroupCode: 'AG2' },
    { ko: '공공기관', en: 'Public institutions', categoryGroupCode: 'PO3' },
    { ko: '숙박', en: 'Lodgment', categoryGroupCode: 'AD5' },
    { ko: '음식점', en: 'Restaurant', categoryGroupCode: 'FD6' },
    { ko: '카페', en: 'Cafe', categoryGroupCode: 'CE7' },
    { ko: '병원', en: 'Hospital', categoryGroupCode: 'HP8' },
    { ko: '약국', en: 'Pharmacy', categoryGroupCode: 'PM9' },
  ],
});
