version: "2.0"

services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    restart: always
    ports:
      - "5000:80"
    env_file:
      - .env
    links:
      - api

  api:
    build: .
    restart: always
    env_file:
      - .env
